const GENERAL: string[] = [
  "Considering the lives you didn't live...",
  "Calculating the apartment you didn't rent...",
  "Reviewing the breakup you didn't have...",
  "Auditing your unwritten LinkedIn posts...",
  "Cross-referencing your parallel divorces...",
  "Locating the job offer you never opened...",
  "Estimating the cities you almost moved to...",
  "Tallying the degrees left unfinished...",
  "Reviewing the texts you almost sent...",
  "Mapping the friendships that faded before they started...",
  "Cataloguing your abandoned side projects...",
  "Projecting the salary you didn't negotiate...",
  "Simulating the flight you didn't book...",
  "Recovering drafts of emails never sent...",
  "Measuring the distance between here and there...",
  "Indexing your untaken sabbaticals...",
  "Estimating the children you didn't have...",
  "Computing the thesis you never finished...",
  "Retrieving the band you almost joined...",
  "Calibrating the startup that almost launched...",
  "Restoring the relationship that almost worked...",
  "Reviewing the conference talks you didn't give...",
  "Locating your PhD from the parallel timeline...",
  "Scanning the passports you didn't fill...",
  "Tracing the road trip that never happened...",
  "Reconstructing the novel in your drawer...",
  "Defragmenting your unused potential...",
  "Compiling the regrets. This may take a moment...",
  "Buffering your alternate commute...",
  "Loading the version of you that said yes...",
  "Syncing the life that didn't need syncing...",
  "Downloading your parallel tax returns...",
  "Verifying the references you never called...",
  "Processing your unchosen graduate programs...",
  "Archiving the performances you never gave...",
  "Rendering the kitchen in your other apartment...",
  "Retrieving the co-founder you almost called...",
  "Calculating years saved by skipping the MBA...",
  "Locating the city where Other You pays less rent...",
  "Reviewing the résumé you threw away...",
  "Reconstructing the move you almost made...",
  "Resolving conflicts in your alternate timeline...",
  "Compressing the years between then and now...",
  "Decompressing the choice you made in a hurry...",
  "Estimating the promotions you didn't ask for...",
  "Loading the conference room you almost owned...",
  "Streaming the TED talk Other You gave...",
  "Validating the fork point data...",
  "Assembling the paper trail of the road not taken...",
  "Searching archived futures for your name...",
  "Rendering the life at a slower pace...",
  "Processing happiness metrics from the other timeline...",
  "Recovering deleted ambitions...",
  "Restoring the draft that changed everything...",
  "Estimating the conference you almost attended...",
  "Counting the hours Other You sleeps...",
  "Locating the version of you that kept the plant alive...",
  "Retrieving the hobby that stuck in the other life...",
  "Cross-checking two timelines for irony...",
  "Assembling Other You's bookshelf...",
];

const ZELDA: string[] = [
  "Reconsidering the divine mandate of 2014...",
  "Calculating the years spent not in a castle...",
  "Reviewing the morning you didn't become a vessel...",
  "Estimating Hyrule's fate without you...",
  "Auditing 100 years of suspended animation...",
  "Locating the Sheikah Slate you left at the lab...",
  "Computing the prophecies that didn't apply...",
  "Tallying the Guardians you didn't have to dodge...",
  "Retrieving your unpublished archaeology paper...",
  "Simulating Hyrule without a chosen one...",
  "Calculating the cottages you could have rented...",
  "Estimating crops grown instead of malice contained...",
  "Reviewing the pumpkins left unharvested...",
  "Locating Hateno Village, your alternate permanent address...",
  "Defragmenting your memories from before the sealing...",
  "Reconstructing the life where Link was just a friend...",
  "Loading the timeline where you kept the Triforce...",
  "Mapping your research career without the interruptions...",
  "Restoring your PhD in Ancient Sheikah Technology...",
  "Rendering the kingdom you decided wasn't your problem...",
  "Downloading your alternate morning routine. No Ganon...",
  "Tracing your expedition to the Spring of Wisdom...",
  "Compiling field notes from a quieter Hyrule...",
  "Estimating the recipes you perfected instead...",
  "Recovering the Divine Beasts you left to someone else...",
  "Locating the parallel Zelda who stayed in Kakariko...",
  "Reviewing the prophecy you politely declined...",
];

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function getOneLinerPool(isDemo: boolean): string[] {
  return shuffle(isDemo ? ZELDA : GENERAL);
}
